server:
  port: 9696


spring:
  datasource:
    driver-class-name: org.h2.Driver
    password: 
    url: jdbc:h2:mem:test
    username: Ashu
    
    
  mvc:
    view:
      prefix: /view/
      suffix: .jsp
      
  app1:
      messages:
       saveSuccess: Contact save Succesfully
       saveFail: Contact Failed To Save